# This is a basic workflow to help you get started with Actions

name: GetProjects

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


// get projects Endpoint

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
    # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with: 
            node-version: '14'
    
    # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra
    # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults


    # Run the Get Projects
      - name: Run Get Projects
        run: |
         newman run .M-Mportal/api/made-and-modern-portal/New Collection.postman_collection(getprojects) -e .M-Mportal/api/made-and-modern-portal/GetProjectEnv.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
    # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with: 
         name: RunReports
         path: testResults
