owner: anu99gupta # GitHub username
repo: upptime # GitHub repository name
sites: # List of endpoints to track
  - name: Made and Modern Portal
    url: https://mam-portal-experimental.web.app/
  - name: https://mam-portal-experimental.web.app/login
    method: POST
    url: https://mam-portal-experimental.web.app/
    headers:
    - "Content-Type: application/json"
    body: '{ "email": "anupama@madeandmodern.com" }{ "password": "Anupama@2021" }'
    

status-website: # Status website (optional)
  cname: https://mam-portal-experimental.web.app/ # Custom domain CNAME
  name: Made and Modern # Status website title

